// SSH config file parsing and generation.
// Frontend owns all parsing — the backend only reads/writes the raw file.

import { invoke } from "@tauri-apps/api/core";
import { logError } from "../core/errorlog";
import type { SshHost } from "../core/types";

// Config-wide sections captured verbatim on parse and written back on
// generate — without this, Save SSH Config silently DELETED them:
//   - the global block before the first Host line (kept at the top)
//   - pure `Host *` blocks (moved to the END, the canonical position:
//     OpenSSH first-match semantics would otherwise let them shadow the
//     host-specific settings that follow them)
// Inheritance still merges these values into every parsed host for
// display; the raw text round-trips alongside.
let globalPreSection = "";
let wildcardSections: string[] = [];

// Scan the raw text for the pre-first-Host block and pure `Host *` blocks.
function captureGlobalSections(raw: string): void {
  const pre: string[] = [];
  const wildcards: string[] = [];
  let block: string[] | null = null;
  let seenHost = false;
  const hostNames = (line: string): string[] =>
    line
      .trim()
      .slice(line.trim().search(/\s/) + 1)
      .trim()
      .split(/\s+/);
  const isPureWildcard = (line: string): boolean => {
    const names = hostNames(line);
    return names.length === 1 && names[0] === "*";
  };

  for (const line of raw.split("\n")) {
    const t = line.trim();
    const isHostLine = /^host\s+/i.test(t) && !t.startsWith("#");
    if (block) {
      if (isHostLine) {
        wildcards.push(block.join("\n").trim());
        block = isPureWildcard(line) ? [line] : null;
      } else {
        block.push(line);
      }
    } else if (!seenHost && !isHostLine) {
      pre.push(line);
    } else if (isHostLine) {
      seenHost = true;
      if (isPureWildcard(line)) block = [line];
    }
  }
  if (block) wildcards.push(block.join("\n").trim());
  globalPreSection = pre.join("\n").trim();
  wildcardSections = wildcards.filter(Boolean);
}

export function parseSshConfig(raw: string): SshHost[] {
  captureGlobalSections(raw);
  const hosts: SshHost[] = [];
  let current: SshHost | null = null;
  const preProps: Record<string, string> = {};
  let wildcardProps: Record<string, string> = {};

  const flush = () => {
    if (!current) return;
    const names = (current as any).__names || [current.name];
    for (const n of names) {
      const h: SshHost = { name: n, ...wildcardProps, ...preProps };
      for (const [k, v] of Object.entries(current)) {
        if (k !== "name" && !(k as any).startsWith("__")) h[k] = v;
      }
      if (n === "*") {
        wildcardProps = { ...h };
        delete (wildcardProps as any).name;
        delete (wildcardProps as any).__names;
      } else {
        hosts.push(h);
      }
    }
  };

  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const spaceIdx = trimmed.search(/\s/);
    if (spaceIdx === -1) continue;
    const rawKey = trimmed.slice(0, spaceIdx);
    const key = rawKey.toLowerCase();
    const value = trimmed.slice(spaceIdx + 1).trim();

    if (key === "host") {
      flush();
      const names = value.split(/\s+/);
      current = { name: names[0], __names: names } as any;
    } else if (current) {
      // ssh keywords are case-insensitive: find an existing property by
      // lowercase name (never the host's own name/__names fields), so
      // "LocalForward" then "localforward" doesn't split into two props
      // and "HostName" then "hostname" keeps last-wins instead of
      // emitting both on save.
      const existing = Object.keys(current).find(
        (k) => k !== "name" && !k.startsWith("__") && k.toLowerCase() === key,
      );
      // Forward directives may repeat (one per rule); merge into a
      // newline-separated value so nothing is lost. Other keywords keep
      // last-wins behavior.
      if (key === "localforward" || key === "remoteforward" || key === "dynamicforward") {
        if (existing) current[existing] += `\n${value}`;
        else current[rawKey] = value;
      } else {
        current[existing ?? rawKey] = value;
      }
    } else {
      preProps[rawKey] = value;
    }
  }
  // flush last host
  flush();
  for (const h of hosts) {
    delete (h as any).__names;
  }
  return hosts;
}

export function generateSshConfig(hosts: SshHost[]): string {
  const lines: string[] = [];
  lines.push("# Generated by TTerm. Original backed up to config.tt.bak");
  lines.push("");
  // Round-trip the config-wide sections captured on parse: pre-Host
  // globals at the top, `Host *` blocks at the end.
  if (globalPreSection) {
    lines.push(globalPreSection);
    lines.push("");
  }
  const emit = (key: string, value: string) => {
    // Multi-line values (merged forward directives) expand back to one
    // directive per line.
    for (const part of value.split("\n")) lines.push(`    ${key} ${part}`);
  };
  for (const h of hosts) {
    lines.push(`Host ${h.name}`);
    const ordered = ["hostname", "user", "port"];
    const written = new Set<string>();
    for (const lk of ordered) {
      const origKey = Object.keys(h).find((k) => k !== "name" && k.toLowerCase() === lk);
      if (origKey) {
        emit(origKey, h[origKey]);
        written.add(origKey);
      }
    }
    for (const [k, v] of Object.entries(h)) {
      if (k === "name" || written.has(k)) continue;
      emit(k, v);
    }
    lines.push("");
  }
  for (const section of wildcardSections) {
    lines.push(section);
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

/** Read the raw SSH config file and parse it. Returns the parsed hosts. */
export async function loadSshHosts(): Promise<SshHost[]> {
  try {
    const raw = await invoke<string>("ssh_read_config_raw");
    if (raw) return parseSshConfig(raw);
  } catch (e) {
    logError("ssh.loadHosts", e);
  }
  return [];
}
