// SSH config file parsing and generation.
// Frontend owns all parsing — the backend only reads/writes the raw file.

import { invoke } from "@tauri-apps/api/core";
import type { SshHost } from "../core/types";
import { logError } from "../core/errorlog";

export function parseSshConfig(raw: string): SshHost[] {
  const hosts: SshHost[] = [];
  let current: SshHost | null = null;
  const preProps: Record<string, string> = {};
  let wildcardProps: Record<string, string> = {};

  const flush = () => {
    if (!current) return;
    const names = (current as any).__names || [current.name];
    for (const n of names) {
      const h: SshHost = { name: n, ...wildcardProps, ...preProps };
      for (const [k, v] of Object.entries(current)) {
        if (k !== "name" && !(k as any).startsWith("__")) h[k] = v;
      }
      if (n === "*") {
        wildcardProps = { ...h };
        delete (wildcardProps as any).name;
        delete (wildcardProps as any).__names;
      } else {
        hosts.push(h);
      }
    }
  };

  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const spaceIdx = trimmed.search(/\s/);
    if (spaceIdx === -1) continue;
    const rawKey = trimmed.slice(0, spaceIdx);
    const key = rawKey.toLowerCase();
    const value = trimmed.slice(spaceIdx + 1).trim();

    if (key === "host") {
      flush();
      const names = value.split(/\s+/);
      current = { name: names[0], __names: names } as any;
    } else if (current) {
      // ssh keywords are case-insensitive: find an existing property by
      // lowercase name (never the host's own name/__names fields), so
      // "LocalForward" then "localforward" doesn't split into two props
      // and "HostName" then "hostname" keeps last-wins instead of
      // emitting both on save.
      const existing = Object.keys(current).find(
        k => k !== "name" && !k.startsWith("__") && k.toLowerCase() === key);
      // Forward directives may repeat (one per rule); merge into a
      // newline-separated value so nothing is lost. Other keywords keep
      // last-wins behavior.
      if (key === "localforward" || key === "remoteforward" || key === "dynamicforward") {
        if (existing) current[existing] += "\n" + value;
        else current[rawKey] = value;
      } else {
        current[existing ?? rawKey] = value;
      }
    } else {
      preProps[rawKey] = value;
    }
  }
  // flush last host
  flush();
  for (const h of hosts) { delete (h as any).__names; }
  return hosts;
}

export function generateSshConfig(hosts: SshHost[]): string {
  const lines: string[] = [];
  lines.push("# Generated by TTerm. Original backed up to config.tt.bak");
  lines.push("");
  const emit = (key: string, value: string) => {
    // Multi-line values (merged forward directives) expand back to one
    // directive per line.
    for (const part of value.split("\n")) lines.push(`    ${key} ${part}`);
  };
  for (const h of hosts) {
    lines.push(`Host ${h.name}`);
    const ordered = ["hostname", "user", "port"];
    const written = new Set<string>();
    for (const lk of ordered) {
      const origKey = Object.keys(h).find(k => k !== "name" && k.toLowerCase() === lk);
      if (origKey) {
        emit(origKey, h[origKey]);
        written.add(origKey);
      }
    }
    for (const [k, v] of Object.entries(h)) {
      if (k === "name" || written.has(k)) continue;
      emit(k, v);
    }
    lines.push("");
  }
  return lines.join("\n") + "\n";
}

/** Read the raw SSH config file and parse it. Returns the parsed hosts. */
export async function loadSshHosts(): Promise<SshHost[]> {
  try {
    const raw = await invoke<string>("ssh_read_config_raw");
    if (raw) return parseSshConfig(raw);
  } catch (e) {
    logError("ssh.loadHosts", e);
  }
  return [];
}
